apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-demo
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello, World!!! > /pod-data/index.html"]
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
      subPath: index.html
  volumes:
  - name: shared-data
    emptyDir: {}