apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
  labels:
    app: MyApp
spec:
  containers:
  - name: nginx-container
    image: kunchalavikram/hello-nginx:v1 
    ports: 
    - containerPort: 80
  - name: flask-container
    image: kunchalavikram/hello-flask:v1 
    ports: 
    - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: multiport-svc
spec:
  selector:
    app: MyApp
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: flask
      protocol: TCP
      port: 81
      targetPort: 5000