apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: test
subjects:
- kind: ServiceAccount
  name: test # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: test
  apiGroup: ""
  

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
      app: myapp
spec:
  serviceAccountName: test
  containers:
    - name: nginx
      image: nginx

---  
kubectl exec -it nginx -- sh

  
CA_CERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
  
curl --cacert $CA_CERT -H "Authorization: Bearer $TOKEN" "https://kubernetes/api/v1/nodes"

