apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: kunchalavikram/go-app-ms:latest
        ports:
        - containerPort: 80