# apiVersion: v1
# kind: Pod
# metadata:
#   name: multi-container-pod
# spec:
#   restartPolicy: Never
#   containers:
#   - name: c1
#     image: ubuntu
#     command: ["/bin/sh"]
#     args: ["-c", "exit 1"]
#   - name: c2
#     image: ubuntu
#     command: ["/bin/sh"]
#     args: ["-c", "exit 1"]

apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: c1
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo c1; sleep 2;done"]
  - name: c2
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo c2; sleep 2;done"]