apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: backend-app
subsets:
  - addresses:
      - ip: 192.168.59.112
    ports:
      - port: 5000

# docker run -d --name web -p 5000:5000 kunchalavikram/sampleflask:v1
# kubectl run -i --tty --image nginx:alpine test-pod --restart=Never --rm -- sh
# curl backend-app