apiVersion: v1
kind: Service
metadata:
  name: externalsvc-dns
  namespace: default
spec:
  type: ExternalName
  externalName:  flask.dev.svc.cluster.local # FQDN
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask
---
apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: flask
  labels:
    app: flask
spec:
  containers:
  - name: flask-container
    image: kunchalavikram/hello-flask:v1
    ports: 
    - containerPort: 5000

# kubectl run -i --tty --image nginx:alpine test-pod --restart=Never --rm -- sh
# curl  externalsvc-dns