apiVersion: v1
kind: ConfigMap
metadata:
  name: my-env
data:
  VARIABLE1: val1
  VARIABLE2: val2
  VARIABLE3: val3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-details
  labels:
    app: database
data:
  name: "Vikram"
  age: "24"
  email: "devopsmadeeasy@outlook.com"

