apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  custom-nginx.conf: |
    server {
      listen       8080;
      server_name  "";
      location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
      }
    }