# kubectl create cm custom-html-page --from-file test/index.html

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: configmap-volume
      mountPath: /usr/share/nginx/html        
  volumes:
  - name: configmap-volume
    configMap:
      name: custom-html-page
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000    
  selector:
    app: nginx
