apiVersion: v1
kind: Pod
metadata:
  name: ambassador
  labels:
    app: ambassador
spec:
  containers:
  - name: application
    image: curlimages/curl
    command: ["/bin/sh"]
    args: ["-c", "while true; do curl -s localhost:8080 ; sleep 2; done"]
  - name: nginx-proxy
    image: kunchalavikram/nginx-proxy:1.0
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
