apiVersion: v1
kind: Pod
metadata:
  name: init-demo-00
  labels:
    app: init
spec:
  initContainers:
  - name: sleeper01
    image: alpine
    command: ['sleep', '5']
  - name: sleeper02
    image: alpine
    command: ['sleep', '10']
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: init-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
    name: http
  selector:
    app: init
