apiVersion: v1
kind: Pod
metadata:
  name: html
  labels:
    app: html
spec:
  initContainers:
  - name: clone
    image: bitnami/git
    command:
    - git
    - clone
    - https://github.com/kunchalavikram1427/simple-html-page.git
    - /tmp
    volumeMounts:
    - name: scratch
      mountPath: "/tmp"
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: scratch
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: scratch
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: html
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: html