apiVersion: v1
kind: Pod
metadata:
  name: init
spec:
  restartPolicy: Never
  containers:
  - name: application
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo 'hello from main container'"]  #; sleep 10m
  # This containers counts from 10 to 0
  initContainers:
  - name: countdown
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", 'i=10; while [ $i -ge 0 ]; do echo $i; sleep 1; i=$(expr $i - 1); done']
    

# kubectl logs -f init -c countdown
# kubectl logs -f init --all-containers