apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: probe
  name: probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
      - name: probes
        image: kunchalavikram/probes:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: APP_NAME
          value: "ProbesDemo"
        - name: APP_PORT
          value: "5000"
        - name: APP_VERSION
          value: "v1.0.1"
        - name: APP_STARTUP_DELAY
          value: "20"
        livenessProbe:
          httpGet:
            path: /liveness
            port: http
          periodSeconds: 5
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: http
          periodSeconds: 5
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
        startupProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 40
---
apiVersion: v1
kind: Service
metadata:
  name: probe
spec:
  type: NodePort
  selector:
    app: probe
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000