apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask
spec:
  containers:
  - name: flask-env
    image: kunchalavikram/flask-env:latest
    ports:
    - containerPort: 5000
    env:
    - name: BACKGROUND_COLOR
      value: "red"
    - name: TEXT_COLOR
      value: "white"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30001
    protocol: TCP
  selector:
    app: flask