apiVersion: v1
kind: Pod
metadata:
  name: env-from-pod-data
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          echo "POD NAME: $POD_NAME"
          echo "POD IP: $POD_IP"
          echo "POD NAMESPACE: $POD_NAMESPACE"
          echo "POD IS RUNNING IN: $NODE_NAME"
          echo "NODE IP: $NODE_IP"
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  restartPolicy: Never
