apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - name: container-1
    image: busybox
    command: ["/bin/sh","-c"]
    args: ["date >> /cache/date.txt ; sleep 1000"]
    volumeMounts:
    - mountPath: /cache
      name: data
  volumes:
  - name: data
    hostPath:
      path: /x/y # /mnt/data
      type: DirectoryOrCreate


# kubectl exec -it hostpath-pod -c container-1 -- sh
# echo Hello world, this is hostPath demo > /cache/temp.txt