apiVersion: v1
kind: Pod
metadata:
  name: test-webserver
spec:
  containers:
  - name: test-webserver
    image: nginx:latest
    volumeMounts:
    - mountPath: /tmp
      name: mydir
    - mountPath: /usr/share/nginx/html/index.html
      name: myfile
  volumes:
  - name: mydir
    hostPath:
      path: /var/test
      type: Directory
  - name: myfile
    hostPath:
      path: /tmp/index.html
      type: Socket