# $ kubectl create secret generic db-credentials --from-literal=DB_USER=admin --from-literal=DB_PASSWORD=admin123 --dry-run=client -o yaml

# echo -n "admin" | base64
# echo -n "admin123" | base64

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
  DB_PASSWORD: YWRtaW4xMjM=
  DB_USER: YWRtaW4=
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/echo"]
    args: ["$(DB_USERNAME)"]
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_USER
---
