# DB_HOST=192.168.99.111
# DB_USER=root
# DB_PASSWORD=my_secret
# DATABASE=test

# kubectl create secret generic db-info --from-file=./db.conf --dry-run=client -o yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 1000"]
    envFrom:
    - secretRef:  # Will not work as expected as whole file is mounted and not the content
        name: db-info
    volumeMounts:
    - name: secret-volume
      # readOnly: true
      mountPath: "/tmp"
  volumes:
  - name: secret-volume
    secret:
      secretName: db-info

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: busybox
# spec:
#   volumes:
#   - name: secret-volume
#     secret:
#       secretName: secret-demo
#   containers:
#   - image: busybox
#     name: busybox
#     command: ["/bin/sh"]
#     args: ["-c", "sleep 600"]
#     volumeMounts:
#     - name: secret-volume
#       mountPath: /mydata