# kubectl create configmap app-config --from-literal=BACKGROUND_COLOR=blue --from-literal=TEXT_COLOR=white 

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: app-config
# data:
#   BACKGROUND_COLOR: "green" # Literals
#   TEXT_COLOR: "yellow"
# ---
apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask
spec:
  containers:
  - name: flask-env
    image: kunchalavikram/flask-env:latest
    ports:
    - containerPort: 5000
    env:
    - name: BACKGROUND_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config    # Search for  configmap 
          key: BACKGROUND_COLOR
    - name: TEXT_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config    # Search for  configmap 
          key: TEXT_COLOR
---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30001
    protocol: TCP
  selector:
    app: flask
