apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deployment 
  labels: 
    app: nginx-backend
spec: 
  replicas: 3 
  selector: 
    matchLabels:
      app: nginx-backend 
  template: 
    metadata:
      labels: 
        app: nginx-backend
    spec:
      containers:
      - name: nginx-container 
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: svc
spec:
  type: ClusterIP
  selector:
    app: nginx-backend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP


# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: frontend-pod
#   labels:
#     app: nginx-frontend
# spec:
#   containers:
#   - name: nginx-container
#     image: nginx 
#     ports:
#       - containerPort: 80