apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: flask-deployment 
  labels: 
    app: flask
spec: 
  replicas: 3 
  selector: 
    matchLabels:
      app: flask
  template: 
    metadata:
      labels: 
        app: flask
    spec:
      containers:
      - name: flask-container 
        image: kunchalavikram/hello-flask:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: lb-flask
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5000
    # nodePort: 32001
    protocol: TCP
  selector:
    app: flask
