apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress-rules
spec:
  ingressClassName: nginx
  rules:
  - host: 
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: hello
            port:
              number: 80
      - path: /devops
        pathType: Prefix
        backend:
          service:
            name: greet
            port:
              number: 80
      - path: /details
        pathType: Prefix
        backend:
          service:
            name: details
            port:
              number: 80

