apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
      - name: shared-volume
        emptyDir: {}
      initContainers:
      - name: busybox
        image: busybox
        volumeMounts:
        - name: shared-volume
          mountPath: /tmp
        command: ["/bin/sh", "-c"]
        args: ["echo '<h1>Hello Kubernetes</h1>' > /tmp/index.html"]
      containers:
      - image: nginx
        name: nginx
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: shared-volume
          mountPath: /usr/share/nginx/html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: nginx       
