apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
  labels:
    app: nginx
spec:
  containers:
  - name: application
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/app.log; sleep 2;done"]
    volumeMounts:
    - name: temp
      mountPath: /var/log
  - name: log-exporter-sidecar
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: temp
      mountPath: /usr/share/nginx/html
  volumes:
  - name: temp 
    emptyDir: {}
