apiVersion: v1
kind: Service
metadata:
  name: clusterip-flask
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask-backend

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: flask-frontend
spec:
  containers:
  - name: flask-frontend-container 
    image: kunchalavikram/sampleflask 
    ports:
      - containerPort: 5000