apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: env
    image: ubuntu
    env:
    - name: MESSAGE
      value: "hello world"
    command: ["/bin/echo"]
    args: ["$(MESSAGE)"]
  restartPolicy: Never

# kubectl run curl --image=curlimages/curl -i --rm --restart=Never -- printenv
# kubectl run -i --tty --image busybox:1.28 dns-test --restart=Never --rm --sh
# kubectl run -i --tty --image nginx:alpine test-pod --restart=Never --rm -- sh
