apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    pods: "2"
    replicationcontrollers: "1"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"

# $ kubectl describe quota object-counts
# Name:                   object-counts
# Namespace:              default      
# Resource                Used  Hard   
# --------                ----  ----   
# configmaps              1     10     
# persistentvolumeclaims  0     4      
# pods                    1     2      
# replicationcontrollers  0     1      
# secrets                 0     10     
# services                1     10
# services.loadbalancers  0     2


# kubectl create deploy nginx --image=nginx --replicas=3
# kubectl get events

# 17s         Warning   FailedCreate        replicaset/nginx-76d6c9b8c   (combined from similar events): Error creating: pods "nginx-76d6c9b8c-2snw6" is 
# forbidden: exceeded quota: object-counts, requested: pods=1, used: pods=2, limited: pods=2