apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: nginx-backend
spec:
  containers:
  - name: nginx-container
    image: nginx 
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: nginx-frontend
spec:
  containers:
  - name: nginx-container
    image: nginx 
    ports:
      - containerPort: 80