apiVersion: v1
kind: Pod
metadata:
  name: go-pod
spec:
  imagePullSecrets:
  - name: private-reg-secret
  containers:
  - name: go-app
    image: kunchalavikram/probes:v1
    imagePullPolicy: Always

# kubectl create secret docker-registry private-reg-secret  --docker-username=kunchalavikram --docker-password=PAT