# echo -n 'admin123' | base64
# YWRtaW4xMjM=
# kubectl create secret generic db-password --from-literal=DB_PASSWORD=admin123 --dry-run=client -o yaml

apiVersion: v1
kind: Secret
metadata:
  name: db-password
data:
  DB_PASSWORD: YWRtaW4xMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tester-config
data:
  DB_HOST: "mysql.default.svc.cluster.local"  
  DB_USER: "root"
  DATABASE: "test"
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: db-tester
# spec:
#   containers:
#   - name: db-tester
#     image: kunchalavikram/db-connector:1.0 
#     envFrom:
#     - configMapRef:
#         name: tester-config
#     - secretRef:
#         name: db-password
#   restartPolicy: Never
# ---
apiVersion: v1
kind: Pod
metadata:
  name: db-tester
spec:
  containers:
  - name: db-tester
    image: kunchalavikram/db-connector:1.0
    env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: tester-config
            key: DB_HOST
      - name: DB_USER
        valueFrom:
          configMapKeyRef:
            name: tester-config
            key: DB_USER
      - name: DATABASE
        valueFrom:
          configMapKeyRef:
            name: tester-config
            key: DATABASE
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-password
            key: DB_PASSWORD
  restartPolicy: Never