apiVersion: v1
kind: Pod
metadata:
  name: mypod
  annotations: { ... }
  labels:                                
    env: dev
spec:
  containers:                            
  - env:                                 
    - name: key
      value: value
    - name: MASTER
      value: https://master.example.com:8443
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:                              
    - containerPort: 5000
      protocol: TCP
    resources: {}
    securityContext: { ... }            
    volumeMounts:                       
    - mountPath: /registry
      name: registry-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-br6yz
      readOnly: true
  imagePullSecrets:
  - name: default
  restartPolicy: Always                 
  serviceAccount: default

  volumes:                              
  - emptyDir: {}
    name: registry-storage
