apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-01
  labels:
    app: myapp
    env: dev
    project: iot
    region: asia
  namespace: default
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports: 
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-02
  labels:
    app: myapp
    env: dev
    project: iot
    region: asia
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports: 
    - containerPort: 80