# echo -n "admin" | base64
# echo -n "admin123" | base64

apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "env"]
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: password

---
# kubectl create secret generic backend-user --from-literal=backend-username='backend-admin'
# kubectl create secret generic db-user --from-literal=db-username='db-admin'

# apiVersion: v1
# kind: Pod
# metadata:
#   name: envvars-multiple-secrets
# spec:
#   containers:
#   - name: envars-test-container
#     image: nginx
#     env:
#     - name: BACKEND_USERNAME
#       valueFrom:
#         secretKeyRef:
#           name: backend-user
#           key: backend-username
#     - name: DB_USERNAME
#       valueFrom:
#         secretKeyRef:
#           name: db-user
#           key: db-username