# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysecret
# type: Opaque
# data:
#   username: YWRtaW4= # admin
# stringData:
#   username: administrator
#   password: admin123

# kubectl create secret generic nginx-conf --from-file=./custom-nginx.conf
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-conf
type: Opaque
stringData:
  custom-nginx.conf: |
    server {
      listen       8080;
      server_name  "";
      location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
      }
    }
--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 8080
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/nginx/conf.d   
  volumes:
  - name: secret-volume
    secret:
      secretName: nginx-conf
      items:
      - key: custom-nginx.conf
        path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31000    
  selector:
    app: nginx
