apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:authenticated 
  request: LS0tLS1CRUdJTiBDRVJUS
  usages:
  - digital signature
  - key encipherment
  - server auth

  