apiVersion: v1
kind: Service
metadata:
  name: externalsvc-dns
spec:
  type: ExternalName
  externalName:  clusterip-flask.prod.svc.cluster.local # FQDN
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-flask
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask
---
apiVersion: v1
kind: Pod
metadata:
  namespace: prod
  name: flask-pod
  labels:
    app: flask
spec:
  containers:
  - name: flask-container
    image: kunchalavikram/hello-flask:v1
    ports: 
    - containerPort: 5000

