apiVersion: v1
kind: Service
metadata:
  name: flask-backend
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: flask-backend
subsets:
  - addresses:
      - ip: 65.0.31.128
    ports:
      - port: 80
