apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: container-1
    image: busybox
    command: ["/bin/sh","-c"]
    args: ["date >> /cache/date.txt ; sleep 1000"]
    volumeMounts:
    - mountPath: /cache
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp # /mnt/data
      type: DirectoryOrCreate


# kubectl exec -it hostpath-pod -c container-1 -- sh
# echo Hello world, this is hostPath demo > /cache/temp.txt