apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: flask-deployment 
  labels: 
    app: flask
spec: 
  replicas: 3 
  selector:
    matchLabels:
      app: flask
  template: 
    metadata:
      labels: 
        app: flask
    spec:
      containers:
      - name: flask-container 
        image: kunchalavikram/sampleflask:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: headless-flask
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask

# kubectl run -i --tty --image busybox:1.28 dns-test --restart=Never --rm
# nslookup headless-flask

# kubectl run -i --tty --image nginx:alpine test-pod --restart=Never --rm -- sh
# curl headless-flask:5000
