apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
  labels:
    app: busybox
    purpose: emptydir-demo
spec:
  containers:
  - name: container-1
    image: busybox
    command: ["/bin/sh","-c"]
    args: ["date >> /cache/date.txt; sleep 1000"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  - name: container-2
    image: busybox
    command: ["/bin/sh","-c"]
    args: ["cat /cache/date.txt; sleep 1000"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    emptyDir: {}

# kubectl exec -it emptydir-pod -c container-2 -- sh
# cat /cache/date.txt
