apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-rc
spec:
  replicas: 4
  selector:
    app: flask
  template:
    metadata:
      name: flask
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: kunchalavikram/sampleflask:v1
        ports:
        - containerPort: 5000